### ISSUE TITLE
Meson server TODO list to integrate with katzenmint-pki

### ISSUE THREAD

**Issue by sc0Vu** [hashcloak/Meson-server#1]
To integrate meson server with katzenmint-pki, we need to make
some changes for the katzenpost server.

I keep the TODO list for updates that might need in Meson server.

Might pending by:
- [ ] https://github.com/hashcloak/katzenmint-pki/pull/24
- [ ] https://github.com/hashcloak/Meson-client/tree/import-katzenpost-client

TODO list:
- [ ] Remove support to non-voting authority.
- [ ] Update `config` to support the katzenmint-pki.
- [ ] Integrate `internal/pki` to the client from katzenmint-pki.
- [ ] Update integration test for mix nodes and providers.
- [ ] Update `README.md`.
